
// This class describes the event that gets generated by
// the BridgeTester bean. 

package sunw.demo.test;

public class BridgeTesterEvent extends java.util.EventObject {

  BridgeTesterEvent(Object source, String stringValue, int intValue) {
    super(source);
    this.stringValue = stringValue;
    this.intValue = intValue;
  }

  public void setInformationValue(String stringValue) { 
    this.stringValue = stringValue;
  }
  
  public void setIntValue(int intValue) {
    this.intValue = intValue;
  }
  
  public String getInformation() {return stringValue;}
  public int getIntValue() { return intValue; }

  // READ-WRITE PARMS... 
  protected String stringValue;
  protected int    intValue;
}
