


OBJS = 	Poly.class \
	PolyTest.class \
	RFunc.class \
	RFuncLib.class \
	Function.class \
	FuncTest.class \
	FuncTest2.class \
	FuncTest3.class

all: $(OBJS)



%.class:%.java
	javac $<